image:
  file: .devcontainer/Dockerfile

tasks:
  - name: Create development environment
    init: just devenv

vscode:
  extensions:
    - ms-python.black-formatter
    - ms-python.python
    - tamasfe.even-better-toml
